# Generated by Django 5.0.3 on 2024-04-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TUTOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('Optimistic', models.IntegerField(blank=True, default=0, null=True)),
                ('Introduction', models.CharField(max_length=300)),
                ('Proficiency', models.CharField(max_length=200)),
            ],
        ),
    ]
