# Generated by Django 5.0.3 on 2024-04-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
