# Generated by Django 5.0.3 on 2024-04-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_detail_tutor_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DETAIL_TUTOR',
        ),
    ]
