# Generated by Django 5.0.3 on 2024-04-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_detailtutor_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DETAILTUTOR',
        ),
    ]
