# Generated by Django 5.0.3 on 2024-04-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_delete_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtutor',
            name='certificate',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
