# Generated by Django 5.0.3 on 2024-04-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_updateinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DETAILTUTOR',
        ),
    ]
