# Generated by Django 5.0.3 on 2024-04-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_detailtutor_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtutor',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
