# Generated by Django 5.0.3 on 2024-05-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAYMENTRECORD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_desc', models.TextField()),
                ('transaction_no', models.CharField(max_length=255)),
                ('response_code', models.CharField(max_length=10)),
            ],
        ),
    ]
