# Generated by Django 5.0.3 on 2024-05-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtutor',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
