# Generated by Django 5.0.3 on 2024-05-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOADVIDEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Toan10', models.CharField(blank=True, max_length=255, null=True)),
                ('Toan11', models.CharField(blank=True, max_length=255, null=True)),
                ('Toan12', models.CharField(blank=True, max_length=255, null=True)),
                ('Ly10', models.CharField(blank=True, max_length=255, null=True)),
                ('Ly11', models.CharField(blank=True, max_length=255, null=True)),
                ('Ly12', models.CharField(blank=True, max_length=255, null=True)),
                ('Hoa10', models.CharField(blank=True, max_length=255, null=True)),
                ('Hoa11', models.CharField(blank=True, max_length=255, null=True)),
                ('Hoa12', models.CharField(blank=True, max_length=255, null=True)),
                ('Van10', models.CharField(blank=True, max_length=255, null=True)),
                ('Van11', models.CharField(blank=True, max_length=255, null=True)),
                ('Van12', models.CharField(blank=True, max_length=255, null=True)),
                ('Anh10', models.CharField(blank=True, max_length=255, null=True)),
                ('Anh11', models.CharField(blank=True, max_length=255, null=True)),
                ('Anh12', models.CharField(blank=True, max_length=255, null=True)),
                ('urlToan10', models.URLField(blank=True, max_length=255, null=True)),
                ('urlToan11', models.URLField(blank=True, max_length=255, null=True)),
                ('urlToan12', models.URLField(blank=True, max_length=255, null=True)),
                ('urlLy10', models.URLField(blank=True, max_length=255, null=True)),
                ('urlLy11', models.URLField(blank=True, max_length=255, null=True)),
                ('urlLy12', models.URLField(blank=True, max_length=255, null=True)),
                ('urlHoa10', models.URLField(blank=True, max_length=255, null=True)),
                ('urlHoa11', models.URLField(blank=True, max_length=255, null=True)),
                ('urlHoa12', models.URLField(blank=True, max_length=255, null=True)),
                ('urlVan10', models.URLField(blank=True, max_length=255, null=True)),
                ('urlVan11', models.URLField(blank=True, max_length=255, null=True)),
                ('urlVan12', models.URLField(blank=True, max_length=255, null=True)),
                ('urlAnh10', models.URLField(blank=True, max_length=255, null=True)),
                ('urlAnh11', models.URLField(blank=True, max_length=255, null=True)),
                ('urlAnh12', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
