# Generated by Django 5.0.3 on 2024-05-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_loadvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtutor',
            name='subject2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='detailtutor',
            name='subject3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
