# Generated by Django 5.0.3 on 2024-05-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_alter_detailtutor_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtutor',
            name='avatar',
            field=models.ImageField(default='img/Empty.png', upload_to='img_avatar/'),
        ),
    ]
