# Generated by Django 5.0.3 on 2024-05-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_alter_detailtutor_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtutor',
            name='avatar',
            field=models.ImageField(upload_to='img_avatar/'),
        ),
        migrations.AlterField(
            model_name='updateavatar',
            name='avatar',
            field=models.ImageField(default='img/Empty.png', upload_to='updateimg/'),
        ),
    ]
