# Generated by Django 5.0.3 on 2024-05-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_detailtutor_avatar_alter_updateavatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateavatar',
            name='avatar',
            field=models.ImageField(default='C:/Users/DELL/Downloads/GiasuWeb/app1/static/img/Empty.png', upload_to='updateimg/'),
        ),
    ]
