# Generated by Django 5.0.3 on 2024-05-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_alter_updateavatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateavatar',
            name='avatar',
            field=models.ImageField(upload_to='updateimg/'),
        ),
    ]
