# Generated by Django 5.0.3 on 2024-05-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_alter_updateavatar_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateinfo',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
