# Generated by Django 5.0.3 on 2024-05-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_remove_updateinfo_date_updateinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateinfo',
            name='Introduction',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
