# Generated by Django 5.0.3 on 2024-05-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_updateinfo_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateinfo',
            name='Introduction',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='updateinfo',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='updateinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='updateimg/'),
        ),
        migrations.AlterField(
            model_name='updateinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='updateinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='updateinfo',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='updateinfo',
            name='sex',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
