# Generated by Django 5.0.3 on 2024-06-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_alter_updateinfo_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='publickey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
