# Generated by Django 5.0.3 on 2024-06-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_paymentrecord_publickey_paymentrecord_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
