# Generated by Django 5.0.3 on 2024-06-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_alter_paymentrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
