# Generated by Django 5.0.3 on 2024-06-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_alter_paymentrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='tutor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
